- copy: src=nginxsetup.sh dest=/usr/sbin/nginxsetup.sh mode=0755

- file: path=/etc/nginx/sites-available state=directory mode=0755

- file: src=/etc/pki/tls/private dest=/etc/ssl/private state=link owner=root group=root

- copy: src=securitymonkey.conf dest=/etc/nginx/sites-available/securitymonkey.conf mode=0644

- name: Set up Nginx
  command: bash -x /usr/sbin/nginxsetup.sh
  args:
    creates: /etc/nginx/sites-enabled/securitymonkey.conf

- name: Start Nginx
  command: systemctl start nginx
