- copy: src=smsetup.sh dest=/usr/sbin/smsetup.sh mode=0755

- name: Preliminary Security Monkey application setup (clone and run setup script)
  command: bash -x /usr/sbin/smsetup.sh
  args:
    creates: /usr/local/src/security_monkey

- name: preparing the dart environment
  file: path=/var/glibc-rpm state=directory mode=0755

- copy: src=dartsetup.sh dest=/usr/sbin/dartsetup.sh mode=0755

- file: path=/usr/local/src/security_monkey/security_monkey/static state=directory mode=0755

- name: dartsetup (Webapp build environment and the build ot the web interface itself)
  command: bash -x /usr/sbin/dartsetup.sh
  args:
    creates: /usr/lib/dart/bin

- copy: src=secmonkey_config.sh dest=/usr/sbin/secmonkey_config.sh mode=0755

- name: Configure Security Monkey application
  shell: export SECURITY_MONKEY_SETTINGS="/usr/local/src/security_monkey/env-config/config-deploy.py" && bash -x /usr/sbin/secmonkey_config.sh
  args:
    creates: /var/lib/pgsql/data/pg_hba.conf.backup
